version: "3.7"
services:
  db:
    build:
      context: ./db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  server:
    build:
      context: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      APICLUSTER_SECRET: '{"username":"postgres","host":"db","dbname":"postgres","password":"password","port":"5432"}'
    volumes:
      - ${PWD}/:/app
      - /app/node_modules
volumes:
  db-data:
